ALTER TABLE blog_draft ADD COLUMN source TEXT NOT NULL DEFAULT '';
ALTER TABLE blog_post ADD COLUMN source TEXT NOT NULL DEFAULT '';
ALTER TABLE blog_post_history ADD COLUMN source TEXT NOT NULL DEFAULT '';
